#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea3Bases2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tarea3bases2")]
	public partial class LinqAzureDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCARRERA(CARRERA instance);
    partial void UpdateCARRERA(CARRERA instance);
    partial void DeleteCARRERA(CARRERA instance);
    partial void InsertESTUDIANTE(ESTUDIANTE instance);
    partial void UpdateESTUDIANTE(ESTUDIANTE instance);
    partial void DeleteESTUDIANTE(ESTUDIANTE instance);
    partial void InsertESTUDIANTEXCARRERA(ESTUDIANTEXCARRERA instance);
    partial void UpdateESTUDIANTEXCARRERA(ESTUDIANTEXCARRERA instance);
    partial void DeleteESTUDIANTEXCARRERA(ESTUDIANTEXCARRERA instance);
    #endregion
		
		public LinqAzureDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["tarea3bases2ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqAzureDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqAzureDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqAzureDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqAzureDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CARRERA> CARRERAs
		{
			get
			{
				return this.GetTable<CARRERA>();
			}
		}
		
		public System.Data.Linq.Table<ESTUDIANTE> ESTUDIANTEs
		{
			get
			{
				return this.GetTable<ESTUDIANTE>();
			}
		}
		
		public System.Data.Linq.Table<ESTUDIANTEXCARRERA> ESTUDIANTEXCARRERAs
		{
			get
			{
				return this.GetTable<ESTUDIANTEXCARRERA>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CantidadEstudiantes")]
		public ISingleResult<CantidadEstudiantesResult> CantidadEstudiantes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CantidadEstudiantesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EstudiantesCarrera")]
		public ISingleResult<EstudiantesCarreraResult> EstudiantesCarrera([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string carrera)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carrera);
			return ((ISingleResult<EstudiantesCarreraResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CantidadEstudiantesAño")]
		public ISingleResult<CantidadEstudiantesAñoResult> CantidadEstudiantesAño([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> año)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), año);
			return ((ISingleResult<CantidadEstudiantesAñoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CantidadEstudiantesCarrera")]
		public ISingleResult<CantidadEstudiantesCarreraResult> CantidadEstudiantesCarrera([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string carrera)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carrera);
			return ((ISingleResult<CantidadEstudiantesCarreraResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CantidadEstudiantesCarreraAño")]
		public ISingleResult<CantidadEstudiantesCarreraAñoResult> CantidadEstudiantesCarreraAño([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string carrera, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> año)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carrera, año);
			return ((ISingleResult<CantidadEstudiantesCarreraAñoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AgregarEstudianteEnCarrera")]
		public int AgregarEstudianteEnCarrera([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> carnetEstudiante, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_carrera, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_ingreso)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carnetEstudiante, id_carrera, fecha_ingreso);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BorrarCarrera")]
		public int BorrarCarrera([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_carrera)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_carrera);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BorrarEstudiante")]
		public int BorrarEstudiante([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> carnet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carnet);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CantidadEstudiantes")]
		public ISingleResult<CantidadEstudiantesResult1> CantidadEstudiantes1()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CantidadEstudiantesResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CantidadEstudiantesAño")]
		public ISingleResult<CantidadEstudiantesAñoResult1> CantidadEstudiantesAño1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> año)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), año);
			return ((ISingleResult<CantidadEstudiantesAñoResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CantidadEstudiantesCarrera")]
		public ISingleResult<CantidadEstudiantesCarreraResult1> CantidadEstudiantesCarrera1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string carrera)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carrera);
			return ((ISingleResult<CantidadEstudiantesCarreraResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CantidadEstudiantesCarreraAño")]
		public ISingleResult<CantidadEstudiantesCarreraAñoResult1> CantidadEstudiantesCarreraAño1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string carrera, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> año)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carrera, año);
			return ((ISingleResult<CantidadEstudiantesCarreraAñoResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EstudiantesCarrera")]
		public ISingleResult<EstudiantesCarreraResult1> EstudiantesCarrera1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string carrera)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carrera);
			return ((ISingleResult<EstudiantesCarreraResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarCarrera")]
		public int InsertarCarrera([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_carrera, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(30)")] string encargado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(50)")] string ubicacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_carrera, nombre, encargado, ubicacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarEstudiante")]
		public int InsertarEstudiante([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> carnet, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(30)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carnet, cedula, nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ModificarCarrera")]
		public int ModificarCarrera([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_carreraViejo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_carreraNuevo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string nombreNuevo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(30)")] string encargadoNuevo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(50)")] string ubicacionNueva)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_carreraViejo, id_carreraNuevo, nombreNuevo, encargadoNuevo, ubicacionNueva);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ModificarEstudiante")]
		public int ModificarEstudiante([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> carnetViejo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> carnetNuevo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cedulaNueva, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(30)")] string nombreNuevo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carnetViejo, carnetNuevo, cedulaNueva, nombreNuevo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MostrarCarreras")]
		public ISingleResult<MostrarCarrerasResult> MostrarCarreras()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MostrarCarrerasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MostrarEstudiantes")]
		public ISingleResult<MostrarEstudiantesResult> MostrarEstudiantes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MostrarEstudiantesResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CARRERA")]
	public partial class CARRERA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_carrera;
		
		private string _nombre;
		
		private int _encargado;
		
		private string _ubicacion;
		
		private EntitySet<ESTUDIANTEXCARRERA> _ESTUDIANTEXCARRERAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_carreraChanging(int value);
    partial void Onid_carreraChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnencargadoChanging(int value);
    partial void OnencargadoChanged();
    partial void OnubicacionChanging(string value);
    partial void OnubicacionChanged();
    #endregion
		
		public CARRERA()
		{
			this._ESTUDIANTEXCARRERAs = new EntitySet<ESTUDIANTEXCARRERA>(new Action<ESTUDIANTEXCARRERA>(this.attach_ESTUDIANTEXCARRERAs), new Action<ESTUDIANTEXCARRERA>(this.detach_ESTUDIANTEXCARRERAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_carrera", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_carrera
		{
			get
			{
				return this._id_carrera;
			}
			set
			{
				if ((this._id_carrera != value))
				{
					this.Onid_carreraChanging(value);
					this.SendPropertyChanging();
					this._id_carrera = value;
					this.SendPropertyChanged("id_carrera");
					this.Onid_carreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_encargado", DbType="Int NOT NULL")]
		public int encargado
		{
			get
			{
				return this._encargado;
			}
			set
			{
				if ((this._encargado != value))
				{
					this.OnencargadoChanging(value);
					this.SendPropertyChanging();
					this._encargado = value;
					this.SendPropertyChanged("encargado");
					this.OnencargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacion", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string ubicacion
		{
			get
			{
				return this._ubicacion;
			}
			set
			{
				if ((this._ubicacion != value))
				{
					this.OnubicacionChanging(value);
					this.SendPropertyChanging();
					this._ubicacion = value;
					this.SendPropertyChanged("ubicacion");
					this.OnubicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CARRERA_ESTUDIANTEXCARRERA", Storage="_ESTUDIANTEXCARRERAs", ThisKey="id_carrera", OtherKey="carrera")]
		public EntitySet<ESTUDIANTEXCARRERA> ESTUDIANTEXCARRERAs
		{
			get
			{
				return this._ESTUDIANTEXCARRERAs;
			}
			set
			{
				this._ESTUDIANTEXCARRERAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ESTUDIANTEXCARRERAs(ESTUDIANTEXCARRERA entity)
		{
			this.SendPropertyChanging();
			entity.CARRERA1 = this;
		}
		
		private void detach_ESTUDIANTEXCARRERAs(ESTUDIANTEXCARRERA entity)
		{
			this.SendPropertyChanging();
			entity.CARRERA1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ESTUDIANTE")]
	public partial class ESTUDIANTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _carnet;
		
		private int _cedula;
		
		private string _nombre;
		
		private System.Data.Linq.Binary _foto;
		
		private System.Data.Linq.Binary _videoCV;
		
		private EntitySet<ESTUDIANTEXCARRERA> _ESTUDIANTEXCARRERAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncarnetChanging(int value);
    partial void OncarnetChanged();
    partial void OncedulaChanging(int value);
    partial void OncedulaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnfotoChanging(System.Data.Linq.Binary value);
    partial void OnfotoChanged();
    partial void OnvideoCVChanging(System.Data.Linq.Binary value);
    partial void OnvideoCVChanged();
    #endregion
		
		public ESTUDIANTE()
		{
			this._ESTUDIANTEXCARRERAs = new EntitySet<ESTUDIANTEXCARRERA>(new Action<ESTUDIANTEXCARRERA>(this.attach_ESTUDIANTEXCARRERAs), new Action<ESTUDIANTEXCARRERA>(this.detach_ESTUDIANTEXCARRERAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carnet", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int carnet
		{
			get
			{
				return this._carnet;
			}
			set
			{
				if ((this._carnet != value))
				{
					this.OncarnetChanging(value);
					this.SendPropertyChanging();
					this._carnet = value;
					this.SendPropertyChanged("carnet");
					this.OncarnetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="Int NOT NULL")]
		public int cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this.OncedulaChanging(value);
					this.SendPropertyChanging();
					this._cedula = value;
					this.SendPropertyChanged("cedula");
					this.OncedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this.OnfotoChanging(value);
					this.SendPropertyChanging();
					this._foto = value;
					this.SendPropertyChanged("foto");
					this.OnfotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_videoCV", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary videoCV
		{
			get
			{
				return this._videoCV;
			}
			set
			{
				if ((this._videoCV != value))
				{
					this.OnvideoCVChanging(value);
					this.SendPropertyChanging();
					this._videoCV = value;
					this.SendPropertyChanged("videoCV");
					this.OnvideoCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ESTUDIANTE_ESTUDIANTEXCARRERA", Storage="_ESTUDIANTEXCARRERAs", ThisKey="carnet", OtherKey="estudiante")]
		public EntitySet<ESTUDIANTEXCARRERA> ESTUDIANTEXCARRERAs
		{
			get
			{
				return this._ESTUDIANTEXCARRERAs;
			}
			set
			{
				this._ESTUDIANTEXCARRERAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ESTUDIANTEXCARRERAs(ESTUDIANTEXCARRERA entity)
		{
			this.SendPropertyChanging();
			entity.ESTUDIANTE1 = this;
		}
		
		private void detach_ESTUDIANTEXCARRERAs(ESTUDIANTEXCARRERA entity)
		{
			this.SendPropertyChanging();
			entity.ESTUDIANTE1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ESTUDIANTEXCARRERA")]
	public partial class ESTUDIANTEXCARRERA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _estudiante;
		
		private int _carrera;
		
		private System.DateTime _fecha_ingreso;
		
		private EntityRef<CARRERA> _CARRERA1;
		
		private EntityRef<ESTUDIANTE> _ESTUDIANTE1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnestudianteChanging(int value);
    partial void OnestudianteChanged();
    partial void OncarreraChanging(int value);
    partial void OncarreraChanged();
    partial void Onfecha_ingresoChanging(System.DateTime value);
    partial void Onfecha_ingresoChanged();
    #endregion
		
		public ESTUDIANTEXCARRERA()
		{
			this._CARRERA1 = default(EntityRef<CARRERA>);
			this._ESTUDIANTE1 = default(EntityRef<ESTUDIANTE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estudiante", DbType="Int NOT NULL")]
		public int estudiante
		{
			get
			{
				return this._estudiante;
			}
			set
			{
				if ((this._estudiante != value))
				{
					if (this._ESTUDIANTE1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnestudianteChanging(value);
					this.SendPropertyChanging();
					this._estudiante = value;
					this.SendPropertyChanged("estudiante");
					this.OnestudianteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carrera", DbType="Int NOT NULL")]
		public int carrera
		{
			get
			{
				return this._carrera;
			}
			set
			{
				if ((this._carrera != value))
				{
					if (this._CARRERA1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncarreraChanging(value);
					this.SendPropertyChanging();
					this._carrera = value;
					this.SendPropertyChanged("carrera");
					this.OncarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_ingreso", DbType="Date NOT NULL")]
		public System.DateTime fecha_ingreso
		{
			get
			{
				return this._fecha_ingreso;
			}
			set
			{
				if ((this._fecha_ingreso != value))
				{
					this.Onfecha_ingresoChanging(value);
					this.SendPropertyChanging();
					this._fecha_ingreso = value;
					this.SendPropertyChanged("fecha_ingreso");
					this.Onfecha_ingresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CARRERA_ESTUDIANTEXCARRERA", Storage="_CARRERA1", ThisKey="carrera", OtherKey="id_carrera", IsForeignKey=true)]
		public CARRERA CARRERA1
		{
			get
			{
				return this._CARRERA1.Entity;
			}
			set
			{
				CARRERA previousValue = this._CARRERA1.Entity;
				if (((previousValue != value) 
							|| (this._CARRERA1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CARRERA1.Entity = null;
						previousValue.ESTUDIANTEXCARRERAs.Remove(this);
					}
					this._CARRERA1.Entity = value;
					if ((value != null))
					{
						value.ESTUDIANTEXCARRERAs.Add(this);
						this._carrera = value.id_carrera;
					}
					else
					{
						this._carrera = default(int);
					}
					this.SendPropertyChanged("CARRERA1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ESTUDIANTE_ESTUDIANTEXCARRERA", Storage="_ESTUDIANTE1", ThisKey="estudiante", OtherKey="carnet", IsForeignKey=true)]
		public ESTUDIANTE ESTUDIANTE1
		{
			get
			{
				return this._ESTUDIANTE1.Entity;
			}
			set
			{
				ESTUDIANTE previousValue = this._ESTUDIANTE1.Entity;
				if (((previousValue != value) 
							|| (this._ESTUDIANTE1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ESTUDIANTE1.Entity = null;
						previousValue.ESTUDIANTEXCARRERAs.Remove(this);
					}
					this._ESTUDIANTE1.Entity = value;
					if ((value != null))
					{
						value.ESTUDIANTEXCARRERAs.Add(this);
						this._estudiante = value.carnet;
					}
					else
					{
						this._estudiante = default(int);
					}
					this.SendPropertyChanged("ESTUDIANTE1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class CantidadEstudiantesResult
	{
		
		private System.Nullable<int> _Cantidad;
		
		public CantidadEstudiantesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	public partial class EstudiantesCarreraResult
	{
		
		private int _carnet;
		
		private int _cedula;
		
		private string _nombre;
		
		private System.Data.Linq.Binary _foto;
		
		private System.Data.Linq.Binary _videoCV;
		
		public EstudiantesCarreraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carnet", DbType="Int NOT NULL")]
		public int carnet
		{
			get
			{
				return this._carnet;
			}
			set
			{
				if ((this._carnet != value))
				{
					this._carnet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="Int NOT NULL")]
		public int cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this._cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="Image")]
		public System.Data.Linq.Binary foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this._foto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_videoCV", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary videoCV
		{
			get
			{
				return this._videoCV;
			}
			set
			{
				if ((this._videoCV != value))
				{
					this._videoCV = value;
				}
			}
		}
	}
	
	public partial class CantidadEstudiantesAñoResult
	{
		
		private System.Nullable<int> _Cantidad;
		
		public CantidadEstudiantesAñoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	public partial class CantidadEstudiantesCarreraResult
	{
		
		private System.Nullable<int> _Cantidad;
		
		public CantidadEstudiantesCarreraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	public partial class CantidadEstudiantesCarreraAñoResult
	{
		
		private System.Nullable<int> _Cantidad;
		
		public CantidadEstudiantesCarreraAñoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	public partial class CantidadEstudiantesResult1
	{
		
		private System.Nullable<int> _Cantidad;
		
		public CantidadEstudiantesResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	public partial class CantidadEstudiantesAñoResult1
	{
		
		private System.Nullable<int> _Cantidad;
		
		public CantidadEstudiantesAñoResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	public partial class CantidadEstudiantesCarreraResult1
	{
		
		private System.Nullable<int> _Cantidad;
		
		public CantidadEstudiantesCarreraResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	public partial class CantidadEstudiantesCarreraAñoResult1
	{
		
		private System.Nullable<int> _Cantidad;
		
		public CantidadEstudiantesCarreraAñoResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	public partial class EstudiantesCarreraResult1
	{
		
		private int _carnet;
		
		private int _cedula;
		
		private string _nombre;
		
		private System.Data.Linq.Binary _foto;
		
		private System.Data.Linq.Binary _videoCV;
		
		public EstudiantesCarreraResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carnet", DbType="Int NOT NULL")]
		public int carnet
		{
			get
			{
				return this._carnet;
			}
			set
			{
				if ((this._carnet != value))
				{
					this._carnet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="Int NOT NULL")]
		public int cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this._cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="Image")]
		public System.Data.Linq.Binary foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this._foto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_videoCV", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary videoCV
		{
			get
			{
				return this._videoCV;
			}
			set
			{
				if ((this._videoCV != value))
				{
					this._videoCV = value;
				}
			}
		}
	}
	
	public partial class MostrarCarrerasResult
	{
		
		private int _id_carrera;
		
		private string _nombre;
		
		private string _encargado;
		
		private string _ubicacion;
		
		public MostrarCarrerasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_carrera", DbType="Int NOT NULL")]
		public int id_carrera
		{
			get
			{
				return this._id_carrera;
			}
			set
			{
				if ((this._id_carrera != value))
				{
					this._id_carrera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_encargado", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string encargado
		{
			get
			{
				return this._encargado;
			}
			set
			{
				if ((this._encargado != value))
				{
					this._encargado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacion", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string ubicacion
		{
			get
			{
				return this._ubicacion;
			}
			set
			{
				if ((this._ubicacion != value))
				{
					this._ubicacion = value;
				}
			}
		}
	}
	
	public partial class MostrarEstudiantesResult
	{
		
		private int _carnet;
		
		private int _cedula;
		
		private string _nombre;
		
		private System.Data.Linq.Binary _foto;
		
		private System.Data.Linq.Binary _videoCV;
		
		public MostrarEstudiantesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carnet", DbType="Int NOT NULL")]
		public int carnet
		{
			get
			{
				return this._carnet;
			}
			set
			{
				if ((this._carnet != value))
				{
					this._carnet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="Int NOT NULL")]
		public int cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this._cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="Image")]
		public System.Data.Linq.Binary foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this._foto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_videoCV", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary videoCV
		{
			get
			{
				return this._videoCV;
			}
			set
			{
				if ((this._videoCV != value))
				{
					this._videoCV = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
