USE [master]
GO

/****** Object:  Database [tarea3bases2]    Script Date: 4/17/2018 7:05:34 PM ******/
CREATE DATABASE [tarea3bases2]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tarea3bases2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [tarea3bases2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [tarea3bases2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [tarea3bases2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [tarea3bases2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [tarea3bases2] SET ARITHABORT OFF 
GO

ALTER DATABASE [tarea3bases2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [tarea3bases2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [tarea3bases2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [tarea3bases2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [tarea3bases2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [tarea3bases2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [tarea3bases2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [tarea3bases2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [tarea3bases2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [tarea3bases2] SET  ENABLE_BROKER 
GO

ALTER DATABASE [tarea3bases2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [tarea3bases2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [tarea3bases2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [tarea3bases2] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [tarea3bases2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [tarea3bases2] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [tarea3bases2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [tarea3bases2] SET RECOVERY FULL 
GO

ALTER DATABASE [tarea3bases2] SET  MULTI_USER 
GO

ALTER DATABASE [tarea3bases2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [tarea3bases2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [tarea3bases2] SET  READ_WRITE 
GO

USE [tarea3bases2 ]
GO

/****** Object:  Table [dbo].[ESTUDIANTE]    Script Date: 4/17/2018 7:30:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ESTUDIANTE](
	[carnet] [int] NOT NULL,
	[cedula] [int] NOT NULL,
	[nombre] [nchar](30) NOT NULL,
	[id_carrera] [int] NULL,
	[foto] [image] NOT NULL,
	[videoCV] [varbinary](max) NOT NULL,
 CONSTRAINT [PK_ESTUDIANTE] PRIMARY KEY CLUSTERED 
(
	[carnet] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [tarea3bases2 ]
GO

/****** Object:  Table [dbo].[CARRERA]    Script Date: 4/17/2018 7:30:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CARRERA](
	[id_carrera] [int] identity(1,1) NOT NULL,
	[nombre] [nchar](20) NOT NULL,
	[encargado] [int] NOT NULL,
	[ubicacion] [nchar](50) NOT NULL,
 CONSTRAINT [PK_CARRERA] PRIMARY KEY CLUSTERED 
(
	[id_carrera] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [tarea3bases2 ]
GO

/****** Object:  Table [dbo].[ESTUDIANTEXCARRERA]    Script Date: 4/17/2018 7:30:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ESTUDIANTEXCARRERA](
	[id] [int] identity(1,1) NOT NULL,
	[estudiante] [int] NOT NULL,
	[carrera] [int] NOT NULL,
	[fecha_ingreso] [date] NOT NULL,
 CONSTRAINT [PK_ESTUDIANTEXCARRERA] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ESTUDIANTEXCARRERA]  WITH CHECK ADD  CONSTRAINT [FK_ESTUDIANTEXCARRERA_CARRERA] FOREIGN KEY([carrera])
REFERENCES [dbo].[CARRERA] ([id_carrera])
GO

ALTER TABLE [dbo].[ESTUDIANTEXCARRERA] CHECK CONSTRAINT [FK_ESTUDIANTEXCARRERA_CARRERA]
GO

ALTER TABLE [dbo].[ESTUDIANTEXCARRERA]  WITH CHECK ADD  CONSTRAINT [FK_ESTUDIANTEXCARRERA_ESTUDIANTE] FOREIGN KEY([estudiante])
REFERENCES [dbo].[ESTUDIANTE] ([carnet])
GO

ALTER TABLE [dbo].[ESTUDIANTEXCARRERA] CHECK CONSTRAINT [FK_ESTUDIANTEXCARRERA_ESTUDIANTE]
GO


